import { mkdirSync, writeFileSync, readFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

export interface SavedReport {
  date: string;
  projectName: string;
  summary: string;
  tasks: Array<{
    description: string;
    sessionCount: number;
    messageCount: number;
    sessionRefs: number[];
  }>;
  /** The full report text as generated by the agent. */
  fullText: string;
  savedAt: string;
}

const BASE = join(homedir(), ".sc", "reports");

function ensureDir(): void {
  if (!existsSync(BASE)) {
    mkdirSync(BASE, { recursive: true });
  }
}

function filePath(projectName: string, date: string): string {
  const safe = projectName.replace(/[/\\:*?"<>|]/g, "_");
  return join(BASE, `${safe}__${date}.json`);
}

export function saveReport(report: SavedReport): void {
  ensureDir();
  writeFileSync(filePath(report.projectName, report.date), JSON.stringify(report, null, 2), "utf-8");
}

export function getReport(projectName: string, date: string): SavedReport | null {
  const fp = filePath(projectName, date);
  if (!existsSync(fp)) return null;
  return JSON.parse(readFileSync(fp, "utf-8"));
}

export function listReports(projectName?: string): SavedReport[] {
  ensureDir();
  const files = readdirSync(BASE).filter((f) => f.endsWith(".json"));
  const reports: SavedReport[] = [];
  for (const f of files) {
    const raw = readFileSync(join(BASE, f), "utf-8");
    try {
      const r = JSON.parse(raw) as SavedReport;
      if (!projectName || r.projectName === projectName) {
        reports.push(r);
      }
    } catch {
      // skip corrupted files
    }
  }
  reports.sort((a, b) => b.date.localeCompare(a.date));
  return reports;
}

export function listReportDates(projectName: string): string[] {
  ensureDir();
  const prefix = projectName.replace(/[/\\:*?"<>|]/g, "_") + "__";
  return readdirSync(BASE)
    .filter((f) => f.startsWith(prefix) && f.endsWith(".json"))
    .map((f) => f.slice(prefix.length, -5))
    .sort()
    .reverse();
}
